config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  mount Ckpages::Engine => "/ckpages"

  resources :collections

  scope :collections do
    root to: "collections#index", as: :user_root
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :collection_items, dependent: :destroy
  accepts_nested_attributes_for :collection_items, allow_destroy: true

  validates :title, presence: true
  validates :collection_items, presence: {message: 'Добавьте пожалуйста хотя бы один элемент коллекции'}
end

app/models/collection_item.rb
class CollectionItem < ActiveRecord::Base
  belongs_to :collection
  belongs_to :collectionable, polymorphic: true, dependent: :destroy, required: true
  accepts_nested_attributes_for :collectionable

  def to_partial_path
    "collection_items/#{collectionable.class.name.underscore}"
  end

  def build_collectionable(args)
    self.collectionable = collectionable_type.constantize.new(args)
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  has_one :collection_item, as: :collectionable

  validates :url, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_one :collection_item, as: :collectionable

  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ckpages/public404_controller.rb
class Ckpages::Public404Controller < Ckpages::Ascendant404Controller
end

app/controllers/ckpages/public_controller.rb
class Ckpages::PublicController < Ckpages::AscendantController
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.includes(:collection_items => :collectionable).order(:id => :desc).all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new()
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      # TODO Заменить на реальные параметры
      params.require(:collection).permit!
      #params.require(:collection).permit(:token, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def new_collections
    'Новые коллекции'
  end

  def popular_collections
    'Популярные коллекции'
  end

end

app/views/ckpages/public404/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">

      <%= link_to 'new page', ckpages.new_page_path(path: "/#{params[:path]}"), class: 'btn btn-warning'  %>

    </div>
  </div>
</div>

app/views/collection_items/_link.html.erb
<div>
  <h3><%= link_to link.collectionable.url, link.collectionable.url %></h3>
</div>

app/views/collection_items/_photo.html.erb
<div>
  <%= image_tag photo.collectionable.image.thumb %>
</div>

app/views/collections/_collection.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <%= collection.title %>
    <small class="pull-right"><%= l collection.created_at, format: :short %></small>
  </div>
  <div class="panel-body">
    <% collection.collection_items.each do |ci| %>
      <%= render ci %>
    <% end %>
    <br>
  </div>
  <div class="panel-footer">
    <small><%= link_to 'Редактировать', edit_collection_path(collection) %></small>
    <small><%= link_to 'Удалить', collection_path(collection), method: :delete, data: { confirm: 'Уверены, что хотите удалить коллекцию?' } %></small>
    <br>
    <script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script><div style="margin-left: -7px" class="yashare-auto-init" data-yashareL10n="ru" data-yashareLink="<%= collection_url(collection) %>" data-yashareType="link" data-yashareQuickServices="vkontakte,facebook,twitter,gplus"></div>
  </div>
</div>

app/views/collections/_form.html.erb
<div class="row">
  <div class="col-sm-7 col-md-6 col-lg-5">
    <%= simple_form_for @collection do |f| %>

      <%= f.error_notification %>

      <%= f.input :title %>

      <%= f.simple_fields_for :collection_items do |ci| %>
        <%= ci.simple_fields_for :collectionable do |c| %>
          <% case ci.object.collectionable_type %>
          <% when 'Photo' %>
            <%= render 'photo_fields', f: ci %>
          <% when 'Link' %>
            <%= render 'link_fields', f: ci %>
          <% end %>
        <% end %>
      <% end %>

      <div id="insert-before" class="btn-group dropdown">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Добавить
        </button>

        <ul class="dropdown-menu" role="menu">
          <li> 
            <%= link_to_add_association 'Добавить ссылку', f, :collection_items, 
              :wrap_object => Proc.new { |collection_item| collection_item.collectionable = Link.new; collection_item }, 
              partial: 'link_fields', :data => {
                "association-insertion-node" => "#insert-before", 
                "association-insertion-traversal" => "closest", 
                "association-insertion-method" => "before"} %> 
          </li>
          <li> 
            <%= link_to_add_association 'Добавить изображение', f, :collection_items,
              :wrap_object => Proc.new { |collection_item| collection_item.collectionable = Photo.new; collection_item }, 
              partial: 'photo_fields', :data => {
                "association-insertion-node" => "#insert-before", 
                "association-insertion-traversal" => "closest", 
                "association-insertion-method" => "before"} %> 
          </li>
        </ul>
      </div>

      <br>
      <%= f.error :collection_items if f.object.errors[:collection_items] %>

      <br>
      <br>

      <%= f.button :submit, class: 'btn-success btn-lg', id: 'button' %>
      &nbsp;&nbsp;
      <%= link_to 'К списку коллекций', collections_path, data: {confirm: 'Уверены, что хотите покинуть страницу без сохранения?'} %>

    <% end %>
  </div>
</div>

app/views/collections/_link_fields.html.erb
<%# TODO https://github.com/nathanvda/cocoon/issues/293 %>

<% if f.object.marked_for_destruction? %>
  <%= hidden_field_tag("#{f.object_name}[_destroy]", '1') %>
<% else %>
  <div class="nested-fields well">
    <%= f.input :collectionable_type, as: :hidden %>
    <%= f.fields_for :collectionable do |c| %>
        <%= c.input :url %>
    <% end %>
    <%= link_to_remove_association "Удалить", f, data: {confirm: 'Уверены, что хотите удалить?'} %>
  </div>
<% end %>

app/views/collections/_photo_fields.html.erb
<%# TODO https://github.com/nathanvda/cocoon/issues/293 %>

<% if f.object.marked_for_destruction? %>
  <%= hidden_field_tag("#{f.object_name}[_destroy]", '1') %>
<% else %>
  <div class="nested-fields well">
    <%= f.input :collectionable_type, as: :hidden %>
      <%= f.fields_for :collectionable do |c| %>
        <%= image_tag c.object.image.thumb, class: 'img-thumbnail', style: 'margin: 0 0 20px 0' if c.object.image %>
        <%= c.input :image %>
        <%= c.input :image_cache, as: :hidden %>
      <% end %>
    <%= link_to_remove_association "Удалить", f, data: {confirm: 'Уверены, что хотите удалить?'} %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<% @meta_title = 'Редактирование коллекции' %>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1><%= @meta_title %></h1>
      </div>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/collections/index.html.erb
<% @meta_title = 'Личные коллекции' %>

<div class="container">
  <div class="row">

    <div class="col-lg-12">
      <div class="page-header">
        <h1><%= @meta_title %></h1>
      </div>
    </div>

    <div class="col-sm-7 col-md-6 col-lg-5">

      <%= link_to "Новая коллекция", main_app.new_collection_path, class: "btn btn-success btn-lg" %>

      <br>
      <br>

      <% @collections.each do |collection| %>
        <%= render collection %>
      <% end %>

    </div>
  </div>
</div>

app/views/collections/new.html.erb
<% @meta_title = 'Создание коллекции' %>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-header">
        <h1><%= @meta_title %></h1>
      </div>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/collections/show.html.erb
<% @meta_title = 'Просмотр коллекции' %>

<div class="container">
  <div class="row">
    <div class="col-sm-7 col-md-6 col-lg-5">

      <div class="page-header">
        <h1><%= @meta_title %></h1>
      </div>

      <%= render @collection %>

      <br>

      <%= link_to 'К списку коллекций', collections_path, class: "btn btn-success btn-lg" %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title><%= @meta_title %></title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Навигация</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Медиа коллекции", main_app.root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/new">Новые</a></li>
            <% if user_signed_in? %>
              <li><%= link_to "Личные", main_app.user_root_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Личный кабинет <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% if user_signed_in? %>
                  <li> <%= link_to "Выход", destroy_session_path(:user), method: :delete %> </li>
                <% else %>
                  <li> <%= link_to "Вход", session_path(:user) %> </li>
                  <li> <%= link_to "Регистрация", new_registration_path(:user) %> </li>
                  <li> <%= link_to "Забыли пароль?", new_password_path(:user) %> </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="hide_empty alert alert-info"><%= notice %></div>
          <div class="hide_empty alert alert-info"><%= alert %></div>
        </div>
      </div>
    </div>

    <%= yield %>

  </body>
</html>